"""Initial migration

Revision ID: 5161a3cac608
Revises: 4c93a6d5e7af
Create Date: 2025-03-24 15:09:22.394914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5161a3cac608'
down_revision: Union[str, None] = '4c93a6d5e7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shortlink_short_link_key', 'shortlink', type_='unique')
    op.create_unique_constraint(None, 'shortlink', ['short_code'])
    op.drop_column('shortlink', 'short_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortlink', sa.Column('short_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shortlink', type_='unique')
    op.create_unique_constraint('shortlink_short_link_key', 'shortlink', ['short_link'])
    # ### end Alembic commands ###
