"""Initial migration

Revision ID: 6bfd6850611a
Revises: 
Create Date: 2025-03-21 14:39:28.389569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfd6850611a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_link', sa.String(), nullable=False),
    sa.Column('short_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortlink')
    # ### end Alembic commands ###
