"""Initial migration

Revision ID: b83754956520
Revises: 442d333933fd
Create Date: 2025-03-24 09:19:43.462553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83754956520'
down_revision: Union[str, None] = '442d333933fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortlink', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('shortlink', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('shortlink', sa.Column('clicks_count', sa.Integer(), nullable=False))
    op.add_column('shortlink', sa.Column('last_clicked_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'shortlink', ['short_link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shortlink', type_='unique')
    op.drop_column('shortlink', 'last_clicked_at')
    op.drop_column('shortlink', 'clicks_count')
    op.drop_column('shortlink', 'expires_at')
    op.drop_column('shortlink', 'created_at')
    # ### end Alembic commands ###
